server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/campusserv
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: ${RABBITMQ_PASSWORD:guest}

app:
  upload-dir: ${UPLOAD_DIR:c:/Users/allen/Desktop/CampuServ/backend/uploads/}


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    ip-address: 127.0.0.1

internal:
  auth:
    secret: ${INTERNAL_SERVICE_SECRET}

---
spring:
  config:
    activate:
      on-profile: local-dev
  jpa:
    hibernate:
      ddl-auto: update

internal:
  auth:
    secret: default_internal_service_secret_knust_campusserv_2026
